### ISSUE TITLE
ボタンのhoverでへんなことしないで

### ISSUE THREAD

**Issue by ogino-hiroyuki** [ogino-hiroyuki/Seiyuka_Website#2]
<img width="678" alt="スクリーンショット 2021-05-04 13 15 13" src="https://user-images.githubusercontent.com/80797558/116960237-c56c7700-acda-11eb-81a4-d8af8b9edc98.png">

特にこのへんさぁ！！

**Comment by y-akmts** [comment]
すぐ直します！！汗汗

**Comment by ogino-hiroyuki** [comment]
OK なおってたわ
